apiVersion: v1.0
kind: DataProduct

name: {{ cookiecutter.project_name }}
id: 550e8400-e29b-41d4-a716-446655440000
domain: {{ cookiecutter.domain }}
status: draft
tenant: otto

team:
  name: "{{ cookiecutter.team_name }}"
  members:
    - username: "{{ cookiecutter.owner_email }}"
      name: "{{ cookiecutter.owner_name }}"
      role: "owner"

support:
  - channel: "teams"
    url: "{{ cookiecutter.teams_channel_url }}"
  - channel: "email"
    url: "mailto:{{ cookiecutter.support_email }}"

description:
  purpose: {{ cookiecutter.purpose_description }}
  limitations: No known limitations.
  usage: {{ cookiecutter.usage_description }}

tags: ['{{ cookiecutter.domain }}']

inputPorts:
  name: {{ cookiecutter.input_port_name }}
  description: "Input stream for returns data."
  type: {{ cookiecutter.input_type }}
  version: 1.0.0
  contractId: 123e4567-e89b-12d3-a456-426614174000
  tags: ["kafka", "returns", "sadp"]
  customProperties:
    - property: "topicName"
      value: "TBD"
    - property: "bootstrapServers"
      value: "TBD"
    - property: "consumerGroup"
      value: "TBD"

outputPorts:
  name: {{ cookiecutter.output_port_name }}
  description: "Output table for data product in BigQuery."
  type: table
  version: 1.0.0
  contractId: 789e4567-e89b-12d3-a456-426614174222
  tags: ["bigquery", "returns", "sadp"]
  customProperties:
    - property: "destination"
      value: "bigquery"
    - property: "projectId"
      value: "${BIGQUERY_OUTPUT_PROJECT_ID}"
    - property: "datasetId"
      value: "${BIGQUERY_OUTPUT_DATASET_ID}"
    - property: "tableId"
      value: "${BIGQUERY_OUTPUT_TABLE}"